### ISSUE TITLE
Make background color clearcolor of director controller

### ISSUE THREAD

**Issue by schunara** [levinunnink/Smooth-Line-View#10]
I have document and want to use this code to make annotations on it. So I want to see my controller in background and have director controller on it. So that user feel that line is drawn on the document.

Thanks in advance

**Comment by jameshoward** [comment]
Can you not simply place this view on top of your other view? We have created an app that does this on top of photographs and it's working fine.

**Comment by schunara** [comment]
Thanks for reply,

yes I simple does that. By [self.view addSubview:director_.view];

director_.view.backgroundColor = [UIColor clearColor];

but can't see my view under it.

**Comment by schunara** [comment]
Got the solution. By taking screen shot of my screen and then converted uiimage to sprite and set it to rendertexture background. It works amazing.

Thank you
