### ISSUE TITLE
Lags noticeably on Retina (iPad)

### ISSUE THREAD

**Issue by iosdeveloper** [levinunnink/Smooth-Line-View#5]
I watched WWDC '12 session #506 and already made sure that
- UIKit set the appropriate scale factor (2.0 on Retina [iPad])
- We use UIGraphicsBeginImageContextWithOptions to draw to bitmap contexts
- We use opaque drawing because it is much faster
- We "never draw more than we actually need to" (We use setNeedsDisplayInRect: )
- We do not redraw the entire CGPath, instead it is flatten to a bitmap
- static content is placed into separate UIView

Code still lags noticeably in performance on Retina (iPad).

**Comment by levinunnink** [comment]
Hmmm. Interesting. I haven't tested this extensively on a retina iPad. I'll look into it.

**Comment by iosdeveloper** [comment]
I have used one of my tickets for Apple DTS, and just forwarded their reply to you.
Subject: "Fwd: Optimizing 2D drawing performance on Retina Display".

**Comment by levinunnink** [comment]
Thanks! I'll integrate the fix into the code.

**Comment by andsmi** [comment]
I've seen this as an issue as well-- I'd love to put the fix in -- wondering what the direction you are going is. I didn't see a pull request

**Comment by levinunnink** [comment]
Just committed this fix. Sorry about the delay. Let me know how it works.

**Comment by andsmi** [comment]
I put this in and speed definitely is improved--however in my implementation I allow the user to change color of the line when they are drawing-- this implementation changes the color of the entire path..looking at maybe saving a background image each time the color is changed (or something) -- not sure....

**Comment by andsmi** [comment]
So I went ahead and stored the path's in an NSMutableArray when the line color or width changes.... and draw them all ... in draw context. It actually seems to do well. I will refine some more and see if this is the correct solutions.

**Comment by levinunnink** [comment]
Sounds good. Go ahead and submit a pull request if you get it working. Thanks!
